### ISSUE TITLE
WordPress debug.log

### ISSUE THREAD

**Issue by elvishp2006** [schliflo/bedrock-docker#15]
My `WP_ENV` is defined as `development` on `docker-compose.yml` and I added `Config::define('WP_DEBUG_LOG', true);` to `config/environments/development.php` on my bedrock, but the debug.log is not being generated, how I can enable it?

**Comment by schliflo** [comment]
Thats because this setting is only used to set the location of PHP's error log:

*app/web/wp/wp-includes/load.php:328*
```php
if ( WP_DEBUG_LOG ) {
    ini_set( 'log_errors', 1 );
    ini_set( 'error_log', WP_CONTENT_DIR . '/debug.log' );
}
```

However PHP's `error_log` is hardcoded to `/docker.stderr` inside Docker containers.
You can use `make logs` to see logging output of all containers or use `make logs app` to see the logs of the app container in specific.

Let me know if this solves your issue.

**Comment by elvishp2006** [comment]
Thank you, it did the job.
